server:
  port: 8083
  address: localhost
spring:
  mvc:
    locale: en    # for logging only (supported values are: en, ru) 

nodes:
  this:
    name: myself
    agentPort: 7801

choicesSource:
  location: ./config/choices.yaml
  autoReloadEnabled: true

choices:
  - group: AnaLog
    plainLogs:
      - path: ${user.dir}/log/${spring.application.name}.log
        title: "AnaLog's own log :-)"