server:
    port: 8083
    address: localhost

nodes:
  this:
    name: myself
    agentPort: 7801

choices:
  - group: АнаЛог
    plainLogs:
      - path: ${user.dir}/log/${spring.application.name}.log
        title: 'Логи АнаЛога :-)'