choices:
  - group: Examples
    localPlainLogsBase: ${user.dir}\log-samples
    plainLogs:
      - path: generated\core.log
        title: $f [generated]
      - path: generated\micro.log
      - path: source\core-source.log
      - path: source\micro-source.log
        selected: true
    compositeLogs:
      - title: 'Test Composite'
        uriName: 'test-composite'
        includes:
          - path: k8s://deploy/restorun-test-deployment
            timestamp: yyyy-MM-dd HH:mm:ss,SSS
          - path: k8s://deploy/alcatraz-test-deployment
            timestamp: HH:mm:ss,SSS
